#!/bin/bash

# Define screenshot directory

TAB_INFO=$(curl http://localhost:9222/json | jq '.[0]')
URL=$(echo $TAB_INFO | jq -r '.url')

SCREENSHOT_PATH="$HOME/Pictures/Screenshots"

# Check if screenshot directory exists, if not, create it
if [ ! -d "$SCREENSHOT_PATH" ]; then
    mkdir -p "$SCREENSHOT_PATH"
    if [ $? -ne 0 ]; then
        echo "Failed to create directory: $SCREENSHOT_PATH"
        exit 1
    fi
fi

# Get the active window ID
WINDOW_ID=$(xdotool getactivewindow)

# Get the active window title
WINDOW_TITLE=$(xdotool getwindowname $WINDOW_ID | sed "s/[\/:*?\"<>|]/-/g")

# Format the timestamp
TIMESTAMP=$(date +%Y%m%d-%H%M%S)

# Filename with replaced problematic characters
FILE_NAME="$TIMESTAMP - $WINDOW_TITLE.png"

# Take a screenshot of a selected area and save it
gnome-screenshot -a -f "$SCREENSHOT_PATH/$FILE_NAME"

if [ $? -eq 0 ]; then
    echo "Screenshot saved as $SCREENSHOT_PATH/$FILE_NAME"
    BIBTEX_ENTRY="@misc{screen_capture_$TIMESTAMP,
  author = {User},
  title = {Screenshot of $WINDOW_TITLE},
  year = {$(date +%Y)},
  month = {$(date +%m)},
  day = {$(date +%d)},
  url = {$URL},
  note = {Accessed: $TIMESTAMP}
}"
    echo "$BIBTEX_ENTRY" > "$SCREENSHOT_PATH/$FILE_NAME.txt"
else
    echo "Failed to save screenshot."
fi
